### ISSUE TITLE
index out of bounds on simple example

### ISSUE THREAD

**Issue by fuchsnj** [alexcrichton/wasm-gc#14]
rust program
```rust
#[no_mangle]
pub fn add_one(x: i32) -> i32 {
    x + 1
}

fn main() {}
```

compiled using `wargo build` from https://github.com/lord/wargo

stacktrace
```
RUST_BACKTRACE=1 wasm-gc example.wasm example.min.wasm

thread 'main' panicked at 'index out of bounds: the len is 19 but the index is 25', /home/nathan/.cargo/git/checkouts/wasm-gc-d84f174ed78190a0/a9adc2d/wasm-gc/src/gc.rs:255:23
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:69
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:58
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::panicking::panic_bounds_check
             at /checkout/src/libcore/panicking.rs:58
  10: wasm_gc::gc::LiveContext::add_global
  11: wasm_gc::gc::LiveContext::add_function
  12: wasm_gc::gc::LiveContext::add_function
  13: wasm_gc::gc::LiveContext::add_function
  14: wasm_gc::gc::LiveContext::add_function
  15: wasm_gc::gc::LiveContext::add_function
  16: wasm_gc::gc::LiveContext::add_function
  17: wasm_gc::gc::LiveContext::add_function
  18: wasm_gc::gc::garbage_collect
  19: wasm_gc::_gc_file
  20: wasm_gc::main
  21: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:99
  22: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:59
  23: __libc_start_main
  24: _start
```

I can provide the wasm file, or anything else that might help reproduce this if needed, thanks.

**Comment by alexcrichton** [comment]
Thanks for the report! Unfortunately I can't seem to reproduce it, but if you could provide the wasm file that'd be great!

**Comment by fuchsnj** [comment]
@alexcrichton 
[example.wasm.zip](https://github.com/alexcrichton/wasm-gc/files/1558037/example.wasm.zip)

this was built in debug mode. Release mode gets a similar error (with different index values)

**Comment by alexcrichton** [comment]
Aha! Are you using the Emscripten target?
